# Generated by Django 5.0.1 on 2024-01-23 16:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=500)),
                ('category', models.CharField(max_length=50)),
                ('img', models.ImageField(upload_to='media/games')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('units', models.IntegerField()),
                ('rating', models.DecimalField(decimal_places=2, max_digits=10)),
                ('available', models.BooleanField()),
                ('created_at', models.DateTimeField(default=datetime.datetime(2024, 1, 23, 16, 50, 55, 949130, tzinfo=datetime.timezone.utc))),
            ],
        ),
    ]
