# Generated by Django 5.0.1 on 2024-02-28 15:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping_games', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 28, 15, 51, 54, 460397, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='game',
            name='img',
            field=models.ImageField(upload_to='apps/shopping_games/static/imgs'),
        ),
    ]
