# Generated by Django 5.0.1 on 2024-03-01 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping_games', '0004_alter_game_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='img',
            field=models.ImageField(upload_to='shopping_games/static/imgs'),
        ),
    ]
